name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      
    - name: Install dependencies
      run: bun install
      
    - name: Build web
      run: bun run build:web
      env:
        EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        
  deploy-mobile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build production
      run: |
        eas build --platform ios --profile production --non-interactive
        eas build --platform android --profile production --non-interactive
        
    - name: Submit to stores
      run: |
        eas submit --platform ios --profile production
        eas submit --platform android --profile production
      if: github.ref == 'refs/heads/main'